version: "3.8"

services:
  app:
        container_name: app
        restart: always
        build: .
        env_file:
          - .env
        ports:
            - 8080:4000
        depends_on: 
            - database
  database:
    container_name: database
    image: postgres:12.8
    restart: always
    environment:
      - POSTGRES_USER=sharauq
      - POSTGRES_PASSWORD=sharauq
      - POSTGRES_DB=apprentice
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: